services:
  db:
    image: postgres:12.1
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:3.2
    restart: always
    ports:
      - 6379:6379
  web:
    build: .
    restart: always 
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/home/app/taskApp
    depends_on:
      - db
      - redis
  
  